services:
  app:
    build: .
    ports:
      - '3000:3000'
    env_file: .env
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - '3306:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  redis:
    image: redis:latest
    ports:
      - '6380:6379'
